version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: my-mysql-project
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_USER: avavav
      MYSQL_PASSWORD: 2296810
      MYSQL_DATABASE: users
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: